services:
  - type: web
    name: learning-app
    env: node
    buildCommand: npm run build:web
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
